### ISSUE TITLE
Uncaught TypeError: sphere1.move is not a function

### ISSUE THREAD

**Issue by Etol1LC** [charlieroberts/atom-marching#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.3
**Thrown From**: [atom-marching](https://github.com/charlieroberts/atom-marching) package 0.0.3

### Stack Trace

Uncaught TypeError: sphere1.move is not a function

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:2

TypeError: sphere1.move is not a function
    at onframe (/packages/atom-marching/lib/main.js:21:7), <anonymous>:2:11)
    at /packages/atom-marching/node_modules/marching/dist/index.js:1701:16)
    at setTimeout (/packages/atom-marching/node_modules/marching/dist/index.js:1534:27)
```

### Commands

```
  2x -1:36.2.0 atom-hydra:toggle (input.hidden-input)
     -1:28.7.0 atom-marching:toggle (input.hidden-input)
     -1:25.5.0 atom-marching:evalLine (input.hidden-input)
  2x -1:24.3.0 core:move-down (input.hidden-input)
     -1:22.6.0 atom-marching:evalBlock (input.hidden-input)
 13x -1:21.2.0 core:move-down (input.hidden-input)
     -1:04.6.0 atom-marching:evalLine (input.hidden-input)
  8x -1:03.2.0 core:move-down (input.hidden-input)
     -0:59.3.0 atom-marching:evalBlock (input.hidden-input)
  4x -0:55.4.0 core:move-left (input.hidden-input)
 15x -0:53.8.0 core:move-right (input.hidden-input)
     -0:40 core:move-left (input.hidden-input)
 26x -0:39.2.0 core:move-down (input.hidden-input)
  6x -0:29.3.0 atom-marching:evalBlock (input.hidden-input)
```

### Non-Core Packages

```
atom-hydra 0.2.14 
atom-marching 0.0.3 
```

**Comment by charlieroberts** [comment]
Hi,

I hadn't updated marching on npm in over a year... that update should is now published. Let me know if installing v1.0.0 via npm fixes your problem. 

I'll try to be better about npm updates for marching in the future; thanks for filing this. - Charlie

**Comment by Etol1LC** [comment]
Hi, 
nope it doesn’t solve the problem… I am getting the same error msg.

Thnx

**Comment by charlieroberts** [comment]
OK, I just pushed another update to the atom package manager. Try one more time and make sure the version installed is 1.0.0; if you can check and make sure the version of marching.js installed is 1.0.0 as well. Thanks!

**Comment by Etol1LC** [comment]
Hi, when installed, via npm install marchingI get marching 1.0 0 is installed. When I go into Atom  the same version, which is like version 0.0.3 is installed. I do not know what is happening... ThanxInviato dal mio dispositivo mobile Huawei-------- Messaggio originale --------Oggetto: Re: [charlieroberts/atom-marching] Uncaught TypeError: sphere1.move is not a function (#1)Da: charlie roberts A: charlieroberts/atom-marching CC: Etol1LC ,Author OK, I just pushed another update to the atom package manager. Try one more time and make sure the version installed is 1.0.0; if you can check and make sure the version of marching.js installed is 1.0.0 as well. Thanks!
