### ISSUE TITLE
Failed to activate the atom-marching package

### ISSUE THREAD

**Issue by Etol1LC** [charlieroberts/atom-marching#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.3
**Thrown From**: [atom-marching](https://github.com/charlieroberts/atom-marching) package 1.0.0

### Stack Trace

Failed to activate the atom-marching package

```
At Cannot find module 'get-pixels'

Error: Cannot find module 'get-pixels'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/atom-marching/node_modules/marching/js/texture.js:2:19)
    at /packages/atom-marching/node_modules/marching/js/texture.js:343:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/atom-marching/node_modules/marching/js/main.js:13:21)
    at /packages/atom-marching/node_modules/marching/js/main.js:330:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/atom-marching/node_modules/marching/js/index.js:3:18)
    at /packages/atom-marching/node_modules/marching/js/index.js:15:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
```

### Commands

```
     -0:02.0 atom-marching:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-hydra 0.2.14 
atom-marching 1.0.0 
```

**Comment by khoparzi** [comment]
My hacky workaround for now is to just go into the marching folder inside node_modules of the plugin and running a `npm install` should get it working. Of course there is nested doubling of packages, but it seems to work.

**Comment by charlieroberts** [comment]
sorry I completely missed this a few months back. Seems like it should be a simple fix, will try and look at it soon. Could also be a good time to update the npm module so there's feature parity with the online version...

**Comment by charlieroberts** [comment]
I think this should be fixed now, let me know if you have a chance to try it!

**Comment by khoparzi** [comment]
It seems to work fine on OSX but the linux install is now complaining about

`Cannot find module 'glsl-sdf-primitives/udtriangle' from`
