### ISSUE TITLE
Uncaught Error: Cannot find module 'gl-vec3'

### ISSUE THREAD

**Issue by PabIOxyz** [charlieroberts/atom-marching#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.4
**Thrown From**: [atom-marching](https://github.com/charlieroberts/atom-marching) package 1.0.1

### Stack Trace

Uncaught Error: Cannot find module 'gl-vec3'

```
At internal/modules/cjs/loader.js:586

Error: Cannot find module 'gl-vec3'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/private/var/folders/tm/s_r6mpfx2j74n3zxgwzc4fqw0000gn/T/AppTranslocation/994392B4-0190-42D7-85A3-8D10BED12813/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/private/var/folders/tm/s_r6mpfx2j74n3zxgwzc4fqw0000gn/T/AppTranslocation/994392B4-0190-42D7-85A3-8D10BED12813/d/Atom.app/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/private/var/folders/tm/s_r6mpfx2j74n3zxgwzc4fqw0000gn/T/AppTranslocation/994392B4-0190-42D7-85A3-8D10BED12813/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/atom-marching/node_modules/marching/js/camera.js:1:169)
    at /packages/atom-marching/node_modules/marching/js/camera.js:240:3)
    at Module.get_Module._compile (/private/var/folders/tm/s_r6mpfx2j74n3zxgwzc4fqw0000gn/T/AppTranslocation/994392B4-0190-42D7-85A3-8D10BED12813/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/private/var/folders/tm/s_r6mpfx2j74n3zxgwzc4fqw0000gn/T/AppTranslocation/994392B4-0190-42D7-85A3-8D10BED12813/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/private/var/folders/tm/s_r6mpfx2j74n3zxgwzc4fqw0000gn/T/AppTranslocation/994392B4-0190-42D7-85A3-8D10BED12813/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/atom-marching/node_modules/marching/js/main.js:2:21)
    at /packages/atom-marching/node_modules/marching/js/main.js:451:3)
    at Module.get_Module._compile (/private/var/folders/tm/s_r6mpfx2j74n3zxgwzc4fqw0000gn/T/AppTranslocation/994392B4-0190-42D7-85A3-8D10BED12813/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/private/var/folders/tm/s_r6mpfx2j74n3zxgwzc4fqw0000gn/T/AppTranslocation/994392B4-0190-42D7-85A3-8D10BED12813/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/private/var/folders/tm/s_r6mpfx2j74n3zxgwzc4fqw0000gn/T/AppTranslocation/994392B4-0190-42D7-85A3-8D10BED12813/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/atom-marching/node_modules/marching/js/index.js:3:18)
    at /packages/atom-marching/node_modules/marching/js/index.js:15:3)
    at Module.get_Module._compile (/private/var/folders/tm/s_r6mpfx2j74n3zxgwzc4fqw0000gn/T/AppTranslocation/994392B4-0190-42D7-85A3-8D10BED12813/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/private/var/folders/tm/s_r6mpfx2j74n3zxgwzc4fqw0000gn/T/AppTranslocation/994392B4-0190-42D7-85A3-8D10BED12813/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
```

### Commands

```
  6x -1:56 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-marching 1.0.1 
autocomplete-glsl 0.2.3 
autocomplete-python 1.16.0 
build 0.70.0 
build-python 0.12.1 
busy-signal 2.0.1 
color-picker 2.3.0 
darkpython-syntax 0.5.0 
file-icons 2.1.41 
ide-python 1.5.0 
platformio-ide-terminal 2.10.0 
terminal-plus 0.14.5 
todo-show 2.3.2 
veda 2.14.2 
```

**Comment by AndyCatch** [comment]
Hello, I followed @khoparzi 's lead and installed all the missing modules as they showed up in error inside Atom. It seemed to clear this error up. I'm writing this just in case any beginner-ish (like myself) users get blocked. 

In your Terminal (you need to be in your user name directory):
`$ cd .atom/packages/atom-marching/node_modules`
// navigates to atom-marching package

then
`$ npm install`
// this * may * not be necessary but it didn't not work :)

then
`$ npm install gl-vec3 glslify @bandaloo/merge-pass glsl-sdf-primitives glsl-superformula glsl-noise glsl-worley`
// this is * I think * all of the missing packages, but I may have missed some. 

If so, it's a case of copying the name of the missing package thrown in the error, searching npm and installing in the node_modules folder.

Hope that helps!

**Comment by khoparzi** [comment]
Adding to the list of missing packages, this worked for me

`npm install gl-vec3 glslify @bandaloo/merge-pass glsl-sdf-primitives glsl-superformula glsl-noise glsl-worley gl-texture2d get-pixels gl-mat4`
