### ISSUE TITLE
Uncaught Error: Cannot find module 'gl-vec3'Require stack:- $ATOM_HOME/packages/atom-marching/n...

### ISSUE THREAD

**Issue by magfoto** [charlieroberts/atom-marching#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.4
**Thrown From**: [atom-marching](https://github.com/charlieroberts/atom-marching) package 1.0.1

### Stack Trace

Uncaught Error: Cannot find module 'gl-vec3'
Require stack:
- /Users/magfoto/.atom/packages/atom-marching/node_modules/marching/js/camera.js
- /Users/magfoto/.atom/packages/atom-marching/node_modules/marching/js/main.js
- /Users/magfoto/.atom/packages/atom-marching/node_modules/marching/js/index.js
- /Users/magfoto/.atom/packages/atom-marching/lib/main.js
- /Users/magfoto/.atom/packages/atom-marching/lib/atom-marching.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html

```
At internal/modules/cjs/loader.js:800

Error: Cannot find module 'gl-vec3'
Require stack:
- /Users/magfoto/.atom/packages/atom-marching/node_modules/marching/js/camera.js
- /Users/magfoto/.atom/packages/atom-marching/node_modules/marching/js/main.js
- /Users/magfoto/.atom/packages/atom-marching/node_modules/marching/js/index.js
- /Users/magfoto/.atom/packages/atom-marching/lib/main.js
- /Users/magfoto/.atom/packages/atom-marching/lib/atom-marching.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149153)
    at /packages/atom-marching/node_modules/marching/js/camera.js:1:169)
    at /packages/atom-marching/node_modules/marching/js/camera.js:240:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149153)
    at /packages/atom-marching/node_modules/marching/js/main.js:2:21)
    at /packages/atom-marching/node_modules/marching/js/main.js:451:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149153)
    at /packages/atom-marching/node_modules/marching/js/index.js:3:18)
    at /packages/atom-marching/node_modules/marching/js/index.js:15:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
```

### Commands

```
     -2:44.1.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-city-lights-syntax.theme-one-dark-ui)
  2x -2:10.2.0 editor:newline (input.hidden-input)
  2x -1:55.5.0 atom-marching:toggle (input.hidden-input)
     -1:31.8.0 core:save (input.hidden-input)
     -1:14.9.0 core:paste (input.hidden-input)
     -1:03.3.0 core:save (input.hidden-input)
     -0:53.3.0 atom-marching:evalLine (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
atom-hydra 0.3.2 
atom-marching 1.0.1 
atom-p5js 0.1.2 
atom-sass 0.4.0 
city-lights-syntax 1.1.8 
color-picker 2.3.0 
language-csound 0.3.7 
language-glsl 2.0.4 
language-openscad 0.4.3 
markdown-preview-enhanced 0.18.11 
nord-atom-syntax 0.10.0 
nord-atom-ui 0.12.0 
svg-preview 0.14.0 
web-audio-api-snippets 1.3.0 
```

**Comment by magfoto** [comment]
Problem solved following these instructions for all missing modules: https://github.com/charlieroberts/atom-marching/issues/3#issuecomment-707805256
